// src/app/components/signup/signup.component.ts
import { Component } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent {

  signupForm = new FormGroup({
    username: new FormControl('', Validators.required),
    email: new FormControl('', Validators.required),
    password: new FormControl('', Validators.required)
  });

  constructor() { }

  onSubmit() {
    console.log(this.signupForm.value);
  }

}

<form class="container" [formGroup]="signupForm" (ngSubmit)="onSubmit()">

  <div class="form-group">
    <label for="username">Username</label>
    <input  type="text" class="form-control"
            id="username" placeholder="Enter a username"
            formControlName="username" >
  </div>

  <div class="form-group">
    <label for="email">Email address</label>
    <input  type="email" class="form-control"
            id="email" placeholder="Enter email"
            formControlName="email" >
  </div>

  <div class="form-group">
    <label for="password">Password</label>
    <input  type="password" class="form-control"
            id="password" placeholder="Password"
            formControlName="password" >
  </div>

  <button type="submit" class="btn btn-primary"
          [disabled]="!signupForm.valid">Submit</button>

</form>

// src/views/Signup.vue
<template>
  <div class="signup container pt-5">
    <form @submit.prevent="signup">
      <div class="form-group">
        <label for="username">Username</label>
        <input
          type="text"
          class="form-control"
          id="username"
          placeholder="Enter a username"
          v-model="user.username"
          required
        >
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          placeholder="Password"
          v-model="user.password"
          required
        >
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</template>

<script>
export default {
  data: () => ({
    user: {
      username: '',
      password: ''
    }
  }),
  methods: {
    signup() {
      console.log('User object', this.user);
      console.log('Username:', this.user.username);
      console.log('Password:', this.user.password);

      console.log('Forms was submitted!');
    }
  }
};
</script>
